MODULE_NAME = "csv_parser"

SCHEDULE_URL = ""
SCHEDULE_MIN_SIZE_BYTES = 30 * 1024
SCHEDULE_LAST_COLUMN = 35
SCHEDULE_LAST_ROW = 134
SCHEDULE_NAME = "schedule.csv"
WEEKDAYS = ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"]

