// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package api

import (
	"github.com/yaattc/automatic-time-table-creation/backend/app/store"
	"sync"
)

// Ensure, that privStoreMock does implement privStore.
// If this is not the case, regenerate this file with moq.
var _ privStore = &privStoreMock{}

// privStoreMock is a mock implementation of privStore.
//
//     func TestSomethingThatUsesprivStore(t *testing.T) {
//
//         // make and configure a mocked privStore
//         mockedprivStore := &privStoreMock{
//             AddTeacherFunc: func(teacher store.Teacher) (string, error) {
// 	               panic("mock out the AddTeacher method")
//             },
//             DeleteTeacherFunc: func(teacherID string) error {
// 	               panic("mock out the DeleteTeacher method")
//             },
//             GetTeacherFullFunc: func(teacherID string) (store.Teacher, error) {
// 	               panic("mock out the GetTeacherFull method")
//             },
//             ListTeachersFunc: func() ([]store.TeacherDetails, error) {
// 	               panic("mock out the ListTeachers method")
//             },
//             SetTeacherPreferencesFunc: func(teacherID string, pref store.TeacherPreferences) error {
// 	               panic("mock out the SetTeacherPreferences method")
//             },
//         }
//
//         // use mockedprivStore in code that requires privStore
//         // and then make assertions.
//
//     }
type privStoreMock struct {
	// AddTeacherFunc mocks the AddTeacher method.
	AddTeacherFunc func(teacher store.Teacher) (string, error)

	// DeleteTeacherFunc mocks the DeleteTeacher method.
	DeleteTeacherFunc func(teacherID string) error

	// GetTeacherFullFunc mocks the GetTeacherFull method.
	GetTeacherFullFunc func(teacherID string) (store.Teacher, error)

	// ListTeachersFunc mocks the ListTeachers method.
	ListTeachersFunc func() ([]store.TeacherDetails, error)

	// SetTeacherPreferencesFunc mocks the SetTeacherPreferences method.
	SetTeacherPreferencesFunc func(teacherID string, pref store.TeacherPreferences) error

	// calls tracks calls to the methods.
	calls struct {
		// AddTeacher holds details about calls to the AddTeacher method.
		AddTeacher []struct {
			// Teacher is the teacher argument value.
			Teacher store.Teacher
		}
		// DeleteTeacher holds details about calls to the DeleteTeacher method.
		DeleteTeacher []struct {
			// TeacherID is the teacherID argument value.
			TeacherID string
		}
		// GetTeacherFull holds details about calls to the GetTeacherFull method.
		GetTeacherFull []struct {
			// TeacherID is the teacherID argument value.
			TeacherID string
		}
		// ListTeachers holds details about calls to the ListTeachers method.
		ListTeachers []struct {
		}
		// SetTeacherPreferences holds details about calls to the SetTeacherPreferences method.
		SetTeacherPreferences []struct {
			// TeacherID is the teacherID argument value.
			TeacherID string
			// Pref is the pref argument value.
			Pref store.TeacherPreferences
		}
	}
	lockAddTeacher            sync.RWMutex
	lockDeleteTeacher         sync.RWMutex
	lockGetTeacherFull        sync.RWMutex
	lockListTeachers          sync.RWMutex
	lockSetTeacherPreferences sync.RWMutex
}

// AddTeacher calls AddTeacherFunc.
func (mock *privStoreMock) AddTeacher(teacher store.Teacher) (string, error) {
	if mock.AddTeacherFunc == nil {
		panic("privStoreMock.AddTeacherFunc: method is nil but privStore.AddTeacher was just called")
	}
	callInfo := struct {
		Teacher store.Teacher
	}{
		Teacher: teacher,
	}
	mock.lockAddTeacher.Lock()
	mock.calls.AddTeacher = append(mock.calls.AddTeacher, callInfo)
	mock.lockAddTeacher.Unlock()
	return mock.AddTeacherFunc(teacher)
}

// AddTeacherCalls gets all the calls that were made to AddTeacher.
// Check the length with:
//     len(mockedprivStore.AddTeacherCalls())
func (mock *privStoreMock) AddTeacherCalls() []struct {
	Teacher store.Teacher
} {
	var calls []struct {
		Teacher store.Teacher
	}
	mock.lockAddTeacher.RLock()
	calls = mock.calls.AddTeacher
	mock.lockAddTeacher.RUnlock()
	return calls
}

// DeleteTeacher calls DeleteTeacherFunc.
func (mock *privStoreMock) DeleteTeacher(teacherID string) error {
	if mock.DeleteTeacherFunc == nil {
		panic("privStoreMock.DeleteTeacherFunc: method is nil but privStore.DeleteTeacher was just called")
	}
	callInfo := struct {
		TeacherID string
	}{
		TeacherID: teacherID,
	}
	mock.lockDeleteTeacher.Lock()
	mock.calls.DeleteTeacher = append(mock.calls.DeleteTeacher, callInfo)
	mock.lockDeleteTeacher.Unlock()
	return mock.DeleteTeacherFunc(teacherID)
}

// DeleteTeacherCalls gets all the calls that were made to DeleteTeacher.
// Check the length with:
//     len(mockedprivStore.DeleteTeacherCalls())
func (mock *privStoreMock) DeleteTeacherCalls() []struct {
	TeacherID string
} {
	var calls []struct {
		TeacherID string
	}
	mock.lockDeleteTeacher.RLock()
	calls = mock.calls.DeleteTeacher
	mock.lockDeleteTeacher.RUnlock()
	return calls
}

// GetTeacherFull calls GetTeacherFullFunc.
func (mock *privStoreMock) GetTeacherFull(teacherID string) (store.Teacher, error) {
	if mock.GetTeacherFullFunc == nil {
		panic("privStoreMock.GetTeacherFullFunc: method is nil but privStore.GetTeacherFull was just called")
	}
	callInfo := struct {
		TeacherID string
	}{
		TeacherID: teacherID,
	}
	mock.lockGetTeacherFull.Lock()
	mock.calls.GetTeacherFull = append(mock.calls.GetTeacherFull, callInfo)
	mock.lockGetTeacherFull.Unlock()
	return mock.GetTeacherFullFunc(teacherID)
}

// GetTeacherFullCalls gets all the calls that were made to GetTeacherFull.
// Check the length with:
//     len(mockedprivStore.GetTeacherFullCalls())
func (mock *privStoreMock) GetTeacherFullCalls() []struct {
	TeacherID string
} {
	var calls []struct {
		TeacherID string
	}
	mock.lockGetTeacherFull.RLock()
	calls = mock.calls.GetTeacherFull
	mock.lockGetTeacherFull.RUnlock()
	return calls
}

// ListTeachers calls ListTeachersFunc.
func (mock *privStoreMock) ListTeachers() ([]store.TeacherDetails, error) {
	if mock.ListTeachersFunc == nil {
		panic("privStoreMock.ListTeachersFunc: method is nil but privStore.ListTeachers was just called")
	}
	callInfo := struct {
	}{}
	mock.lockListTeachers.Lock()
	mock.calls.ListTeachers = append(mock.calls.ListTeachers, callInfo)
	mock.lockListTeachers.Unlock()
	return mock.ListTeachersFunc()
}

// ListTeachersCalls gets all the calls that were made to ListTeachers.
// Check the length with:
//     len(mockedprivStore.ListTeachersCalls())
func (mock *privStoreMock) ListTeachersCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockListTeachers.RLock()
	calls = mock.calls.ListTeachers
	mock.lockListTeachers.RUnlock()
	return calls
}

// SetTeacherPreferences calls SetTeacherPreferencesFunc.
func (mock *privStoreMock) SetTeacherPreferences(teacherID string, pref store.TeacherPreferences) error {
	if mock.SetTeacherPreferencesFunc == nil {
		panic("privStoreMock.SetTeacherPreferencesFunc: method is nil but privStore.SetTeacherPreferences was just called")
	}
	callInfo := struct {
		TeacherID string
		Pref      store.TeacherPreferences
	}{
		TeacherID: teacherID,
		Pref:      pref,
	}
	mock.lockSetTeacherPreferences.Lock()
	mock.calls.SetTeacherPreferences = append(mock.calls.SetTeacherPreferences, callInfo)
	mock.lockSetTeacherPreferences.Unlock()
	return mock.SetTeacherPreferencesFunc(teacherID, pref)
}

// SetTeacherPreferencesCalls gets all the calls that were made to SetTeacherPreferences.
// Check the length with:
//     len(mockedprivStore.SetTeacherPreferencesCalls())
func (mock *privStoreMock) SetTeacherPreferencesCalls() []struct {
	TeacherID string
	Pref      store.TeacherPreferences
} {
	var calls []struct {
		TeacherID string
		Pref      store.TeacherPreferences
	}
	mock.lockSetTeacherPreferences.RLock()
	calls = mock.calls.SetTeacherPreferences
	mock.lockSetTeacherPreferences.RUnlock()
	return calls
}
