// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package api

import (
	"github.com/yaattc/automatic-time-table-creation/backend/app/store"
	"sync"
)

// Ensure, that privStoreMock does implement privStore.
// If this is not the case, regenerate this file with moq.
var _ privStore = &privStoreMock{}

// privStoreMock is a mock implementation of privStore.
//
//     func TestSomethingThatUsesprivStore(t *testing.T) {
//
//         // make and configure a mocked privStore
//         mockedprivStore := &privStoreMock{
//             AddTeacherFunc: func(teacher store.Teacher) (string, error) {
// 	               panic("mock out the AddTeacher method")
//             },
//             DeleteTeacherFunc: func(teacherID string) error {
// 	               panic("mock out the DeleteTeacher method")
//             },
//             GetTeacherFunc: func(teacherID string) (store.Teacher, error) {
// 	               panic("mock out the GetTeacher method")
//             },
//             ListTeachersFunc: func() ([]store.Teacher, error) {
// 	               panic("mock out the ListTeachers method")
//             },
//             SetPreferencesFunc: func(teacherID string, pref store.TeacherPreferences) error {
// 	               panic("mock out the SetPreferences method")
//             },
//         }
//
//         // use mockedprivStore in code that requires privStore
//         // and then make assertions.
//
//     }
type privStoreMock struct {
	// AddTeacherFunc mocks the AddTeacher method.
	AddTeacherFunc func(teacher store.Teacher) (string, error)

	// DeleteTeacherFunc mocks the DeleteTeacher method.
	DeleteTeacherFunc func(teacherID string) error

	// GetTeacherFunc mocks the GetTeacher method.
	GetTeacherFunc func(teacherID string) (store.Teacher, error)

	// ListTeachersFunc mocks the ListTeachers method.
	ListTeachersFunc func() ([]store.Teacher, error)

	// SetPreferencesFunc mocks the SetPreferences method.
	SetPreferencesFunc func(teacherID string, pref store.TeacherPreferences) error

	// calls tracks calls to the methods.
	calls struct {
		// AddTeacher holds details about calls to the AddTeacher method.
		AddTeacher []struct {
			// Teacher is the teacher argument value.
			Teacher store.Teacher
		}
		// DeleteTeacher holds details about calls to the DeleteTeacher method.
		DeleteTeacher []struct {
			// TeacherID is the teacherID argument value.
			TeacherID string
		}
		// GetTeacher holds details about calls to the GetTeacher method.
		GetTeacher []struct {
			// TeacherID is the teacherID argument value.
			TeacherID string
		}
		// ListTeachers holds details about calls to the ListTeachers method.
		ListTeachers []struct {
		}
		// SetPreferences holds details about calls to the SetPreferences method.
		SetPreferences []struct {
			// TeacherID is the teacherID argument value.
			TeacherID string
			// Pref is the pref argument value.
			Pref store.TeacherPreferences
		}
	}
	lockAddTeacher     sync.RWMutex
	lockDeleteTeacher  sync.RWMutex
	lockGetTeacher     sync.RWMutex
	lockListTeachers   sync.RWMutex
	lockSetPreferences sync.RWMutex
}

// AddTeacher calls AddTeacherFunc.
func (mock *privStoreMock) AddTeacher(teacher store.Teacher) (string, error) {
	if mock.AddTeacherFunc == nil {
		panic("privStoreMock.AddTeacherFunc: method is nil but privStore.AddTeacher was just called")
	}
	callInfo := struct {
		Teacher store.Teacher
	}{
		Teacher: teacher,
	}
	mock.lockAddTeacher.Lock()
	mock.calls.AddTeacher = append(mock.calls.AddTeacher, callInfo)
	mock.lockAddTeacher.Unlock()
	return mock.AddTeacherFunc(teacher)
}

// AddTeacherCalls gets all the calls that were made to AddTeacher.
// Check the length with:
//     len(mockedprivStore.AddTeacherCalls())
func (mock *privStoreMock) AddTeacherCalls() []struct {
	Teacher store.Teacher
} {
	var calls []struct {
		Teacher store.Teacher
	}
	mock.lockAddTeacher.RLock()
	calls = mock.calls.AddTeacher
	mock.lockAddTeacher.RUnlock()
	return calls
}

// DeleteTeacher calls DeleteTeacherFunc.
func (mock *privStoreMock) DeleteTeacher(teacherID string) error {
	if mock.DeleteTeacherFunc == nil {
		panic("privStoreMock.DeleteTeacherFunc: method is nil but privStore.DeleteTeacher was just called")
	}
	callInfo := struct {
		TeacherID string
	}{
		TeacherID: teacherID,
	}
	mock.lockDeleteTeacher.Lock()
	mock.calls.DeleteTeacher = append(mock.calls.DeleteTeacher, callInfo)
	mock.lockDeleteTeacher.Unlock()
	return mock.DeleteTeacherFunc(teacherID)
}

// DeleteTeacherCalls gets all the calls that were made to DeleteTeacher.
// Check the length with:
//     len(mockedprivStore.DeleteTeacherCalls())
func (mock *privStoreMock) DeleteTeacherCalls() []struct {
	TeacherID string
} {
	var calls []struct {
		TeacherID string
	}
	mock.lockDeleteTeacher.RLock()
	calls = mock.calls.DeleteTeacher
	mock.lockDeleteTeacher.RUnlock()
	return calls
}

// GetTeacher calls GetTeacherFunc.
func (mock *privStoreMock) GetTeacher(teacherID string) (store.Teacher, error) {
	if mock.GetTeacherFunc == nil {
		panic("privStoreMock.GetTeacherFunc: method is nil but privStore.GetTeacher was just called")
	}
	callInfo := struct {
		TeacherID string
	}{
		TeacherID: teacherID,
	}
	mock.lockGetTeacher.Lock()
	mock.calls.GetTeacher = append(mock.calls.GetTeacher, callInfo)
	mock.lockGetTeacher.Unlock()
	return mock.GetTeacherFunc(teacherID)
}

// GetTeacherCalls gets all the calls that were made to GetTeacher.
// Check the length with:
//     len(mockedprivStore.GetTeacherCalls())
func (mock *privStoreMock) GetTeacherCalls() []struct {
	TeacherID string
} {
	var calls []struct {
		TeacherID string
	}
	mock.lockGetTeacher.RLock()
	calls = mock.calls.GetTeacher
	mock.lockGetTeacher.RUnlock()
	return calls
}

// ListTeachers calls ListTeachersFunc.
func (mock *privStoreMock) ListTeachers() ([]store.Teacher, error) {
	if mock.ListTeachersFunc == nil {
		panic("privStoreMock.ListTeachersFunc: method is nil but privStore.ListTeachers was just called")
	}
	callInfo := struct {
	}{}
	mock.lockListTeachers.Lock()
	mock.calls.ListTeachers = append(mock.calls.ListTeachers, callInfo)
	mock.lockListTeachers.Unlock()
	return mock.ListTeachersFunc()
}

// ListTeachersCalls gets all the calls that were made to ListTeachers.
// Check the length with:
//     len(mockedprivStore.ListTeachersCalls())
func (mock *privStoreMock) ListTeachersCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockListTeachers.RLock()
	calls = mock.calls.ListTeachers
	mock.lockListTeachers.RUnlock()
	return calls
}

// SetPreferences calls SetPreferencesFunc.
func (mock *privStoreMock) SetPreferences(teacherID string, pref store.TeacherPreferences) error {
	if mock.SetPreferencesFunc == nil {
		panic("privStoreMock.SetPreferencesFunc: method is nil but privStore.SetPreferences was just called")
	}
	callInfo := struct {
		TeacherID string
		Pref      store.TeacherPreferences
	}{
		TeacherID: teacherID,
		Pref:      pref,
	}
	mock.lockSetPreferences.Lock()
	mock.calls.SetPreferences = append(mock.calls.SetPreferences, callInfo)
	mock.lockSetPreferences.Unlock()
	return mock.SetPreferencesFunc(teacherID, pref)
}

// SetPreferencesCalls gets all the calls that were made to SetPreferences.
// Check the length with:
//     len(mockedprivStore.SetPreferencesCalls())
func (mock *privStoreMock) SetPreferencesCalls() []struct {
	TeacherID string
	Pref      store.TeacherPreferences
} {
	var calls []struct {
		TeacherID string
		Pref      store.TeacherPreferences
	}
	mock.lockSetPreferences.RLock()
	calls = mock.calls.SetPreferences
	mock.lockSetPreferences.RUnlock()
	return calls
}
